title: huystuhh.github.io
description: One of the personal websites of all time.
email: huydngo@outlook.com
domain: "huystuhh.github.io"
url: "http://huystuhh.github.io"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
